execution:
  dependencies: []
  entry_point: main.py::execute
metadata:
  author: '{{author}}'
  created_date: '{{date}}'
tool:
  description: '{{description}}'
  name: '{{tool_name}}'
  type: dcc
  version: 1.0.0
